### ISSUE TITLE
Handling reRouting with React-Router

### ISSUE THREAD

**Issue by ghost** [psibi/yesod-rest#4]
First thank you for the good example and project

I am using React-Router in our React application.
I am wondering how the rerouting would be handled with this solution.
For example if we have a route /login, we would like to be able the user to type the complete url and be directed to the right application of the react part.

I would think that it will require all routes to serve the same handler with the react application.

Vincent

**Comment by psibi** [comment]
Sorry, I don't have experience with react-router. But I think your assumption is correct. But I can't be really sure.

**Comment by psibi** [comment]
I'm closing the issue. But I would be glad to hear your experience here. Please re-open the issue if required.

**Comment by ghost** [comment]
Hi,

One way to make this work is to define the same routes both in react router
and Yesod. It adds some boilerplate code though.

Vincent
